<?php

return [
    'contact' => [
        'title' => 'Contact Us',
        'subtitle' => 'Get in touch with us today!',
        'description' => 'Send us a message using the form below and we will get back to you as soon as possible.',
        'bg_color' => '#fff',
        'image' => 'contact-us.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'contact',
        'details' => 'Send us a message using the form below and we will get back to you as soon as possible.',
        'meta_title' => 'contact',
        'meta_description' => 'contact',
        'link' => 'www.google.com',
    ],
    'about' => [
        'title' => 'About Us',
        'subtitle' => 'Learn more about our company',
        'description' => 'We are a team of dedicated professionals who are passionate about what we do. Learn more about our history, values, and mission.',
        'bg_color' => '#fafafa',
        'image' => 'contact-us.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'contact',
        'details' => 'Send us a message using the form below and we will get back to you as soon as possible.',
        'meta_title' => 'contact',
        'meta_description' => 'contact',
        'link' => 'www.google.com',
    ],
   'privacy' => [
        'name' => 'Privacy Policy',
        'title' => 'Privacy Policy',
        'subtitle' => 'Protecting your privacy is important to us',
        'description' => 'Read about our privacy practices and how we protect your personal information.',
        'bg_color' => '#fff',
        'image' => 'privacy.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'privacy',
        'details' => 'Read about our privacy practices and how we protect your personal information.',
        'meta_title' => 'Privacy Policy',
        'meta_description' => 'Protecting your privacy is important to us',
        'link' => 'www.company.com/privacy',
        ],
];
