<?php

return [
    'contact' => [
        'title' => 'Contact Us',
        'subtitle' => 'Get in touch with us today!',
        'description' => 'Send us a message using the form below and we will get back to you as soon as possible.',
        'bg_color' => '#fff',
        'image' => 'contact-us.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'contact',
        'details' => 'Send us a message using the form below and we will get back to you as soon as possible.',
        'meta_title' => 'contact',
        'meta_description' => 'contact',
        'link' => 'www.google.com',
    ],
    'about' => [
        'title' => 'About Us',
        'subtitle' => 'Learn more about our company',
        'description' => 'We are a team of dedicated professionals who are passionate about what we do. Learn more about our history, values, and mission.',
        'bg_color' => '#fafafa',
        'image' => 'contact-us.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'contact',
        'details' => 'Send us a message using the form below and we will get back to you as soon as possible.',
        'meta_title' => 'contact',
        'meta_description' => 'contact',
        'link' => 'www.google.com',
    ],
   'privacy' => [
        'name' => 'Privacy Policy',
        'title' => 'Privacy Policy',
        'subtitle' => 'Protecting your privacy is important to us',
        'description' => 'Read about our privacy practices and how we protect your personal information.',
        'bg_color' => '#fff',
        'image' => 'privacy.jpg',
        'featured_title' => 'title',
        'label' => 'some',
        'position' => '1',
        'slug' => 'privacy',
        'details' => 'Read about our privacy practices and how we protect your personal information.',
        'meta_title' => 'Privacy Policy',
        'meta_description' => 'Protecting your privacy is important to us',
        'link' => 'www.company.com/privacy',
    ],
    'terms' => [
        'name' => 'Terms and Conditions',
        'title' => 'Terms and Conditions',
        'subtitle' => 'Please read these terms and conditions carefully',
        'description' => 'This page outlines the terms and conditions that govern the use of our website and services.',
        'bg_color' => '#fff',
        'image' => 'terms.jpg',
        'featured_title' => 'Terms and Conditions',
        'label' => 'some',
        'position' => '3',
        'slug' => 'terms-and-conditions',
        'details' => 'This page outlines the terms and conditions that govern the use of our website and services.',
        'meta_title'=> 'Terms and Conditions',
        'meta_description' => 'Please read these terms and conditions carefully',
        'link' => 'www.company.com/terms-and-conditions',
    ],
    'shipping' => [
        'name' => 'Shipping and Returns',
        'title' => 'Shipping and Returns',
        'subtitle' => 'Information about our shipping and returns policies',
        'description' => 'This page provides information on our shipping and returns policies, including delivery times, shipping options, and returns procedures.',
        'bg_color' => '#fff',
        'image' => 'shipping-returns.jpg',
        'featured_title' => 'Shipping and Returns',
        'label' => 'some',
        'position' => '4',
        'slug' => 'shipping-and-returns',
        'details' => 'This page provides information on our shipping and returns policies, including delivery times, shipping options, and returns procedures.',
        'meta_title' => 'Shipping and Returns',
        'meta_description' => 'Information about our shipping and returns policies',
        'link' => 'www.company.com/shipping-and-returns',
    ],
    'faq' => [
        'name' => 'FAQ',
        'title' => 'Frequently Asked Questions',
        'subtitle' => 'Answers to common questions',
        'description' => 'This page provides answers to frequently asked questions about our products, services, and policies.',
        'bg_color' => '#fff',
        'image' => 'faq.jpg',
        'featured_title' => 'Frequently Asked Questions',
        'label' => 'some',
        'position' => '5',
        'slug' => 'faq',
        'details' => 'This page provides answers to frequently asked questions about our products, services, and policies.',
        'meta_title' => 'Frequently Asked Questions',
        'meta_description' => 'Answers to common questions',
        'link' => 'www.company.com/faq',
    ],

];
